// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuyckkzhibhfagvtiizb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1eWNra3poaWJoZmFndnRpaXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTg1NTIsImV4cCI6MjA2MDgzNDU1Mn0.eM4c_0K2GMeyuCfkcXQhQko7uGb5Abkngzf5pe9hKs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);